# Generated by Django 5.2.0 on 2026-04-23 11:35

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='SMTP server address (e.g., smtp.gmail.com)', max_length=255)),
                ('email_address', models.CharField(help_text='Sender email address', max_length=255)),
                ('email_password', models.CharField(help_text='SMTP password or app-specific password', max_length=255)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP port (usually 587 for TLS, 465 for SSL)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (mutually exclusive with TLS)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-created_at'],
            },
        ),
    ]
