# Generated by Django 4.2.30 on 2026-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Configuration', 'verbose_name_plural': 'Email Configuration'},
        ),
        migrations.RemoveField(
            model_name='emailconfiguration',
            name='use_ssl',
        ),
    ]
