# Generated by Django 4.2.30 on 2026-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_emailconfiguration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_icon', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('university_logo', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('seal', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('collaborator_logo', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='certificate_template/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'verbose_name_plural': 'Certificate Template',
            },
        ),
    ]
