# Generated by Django 4.2.30 on 2026-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='endorser_first_designation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='endorser_second_designation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='professor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
