# Generated by Django 4.2.30 on 2026-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_rename_proffessor_to_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='admin_notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive admin notifications (e.g. question generation alerts)', max_length=255, null=True),
        ),
    ]
