# Generated by Django 4.2.30 on 2026-06-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_emailconfiguration_admin_notification_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfiguration',
            name='admin_notification_email',
        ),
    ]
