#!/bin/bash

echo "=========================================="
echo "Stripe Webhook Integration Setup"
echo "=========================================="
echo ""

echo "Step 1: Creating migrations..."
python manage.py makemigrations enrollment

echo ""
echo "Step 2: Applying migrations..."
python manage.py migrate

echo ""
echo "Step 3: Populating subscription plans..."
python manage.py populate_subscription_plans

echo ""
echo "=========================================="
echo "✅ Stripe Webhook Integration Setup Complete!"
echo "=========================================="
echo ""
echo "Next Steps:"
echo ""
echo "1. Configure Stripe credentials in .env:"
echo "   STRIPE_SECRET_KEY=sk_test_xxxxxxxxxxxxx"
echo "   STRIPE_PUBLISHABLE_KEY=pk_test_xxxxxxxxxxxxx"
echo "   STRIPE_WEBHOOK_SECRET=whsec_xxxxxxxxxxxxx"
echo ""
echo "2. Setup Stripe webhook:"
echo "   - Go to: https://dashboard.stripe.com/webhooks"
echo "   - Add endpoint: https://yourdomain.com/enrollment/stripe/webhook/"
echo "   - Select events:"
echo "     * invoice.payment_succeeded"
echo "     * invoice.payment_failed"
echo "     * customer.subscription.updated"
echo "     * customer.subscription.deleted"
echo "     * charge.succeeded"
echo "     * charge.failed"
echo "   - Copy webhook signing secret to .env"
echo ""
echo "3. Test webhook locally with Stripe CLI:"
echo "   stripe listen --forward-to localhost:8000/enrollment/stripe/webhook/"
echo "   stripe trigger invoice.payment_succeeded"
echo ""
echo "4. View subscription plans:"
echo "   GET /enrollment/plans/"
echo ""
echo "5. Admin can modify pricing at:"
echo "   http://localhost:8000/admin/enrollment/subscriptionplan/"
echo ""
echo "6. View Swagger documentation:"
echo "   http://localhost:8000/swagger/"
echo ""
