# Generated by Django 6.0.3 on 2026-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(help_text='Stripe secret key used for server-side operations', max_length=255)),
                ('stripe_publishable_key', models.CharField(help_text='Stripe publishable key used on the client side', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Configuration',
                'verbose_name_plural': 'Stripe Configuration',
                'ordering': ['-created_at'],
            },
        ),
    ]
